### ISSUE TITLE
关于文章发表时间

### ISSUE THREAD

**Issue by 1580827935** [wjiazheng/SwinPA-Net#1]
关于文章发表时间，Date of Publication: September 2022 和Published in April 2024。两者的区别是什么？若我引用这篇文章，这篇文章当属2022年还是2024年？
【一个小白问题，虚心向您请教】
![图片](https://github.com/wjiazheng/SwinPA-Net/assets/117509706/e1914fe0-8bb4-408e-8f3b-594cd8e63cc7)

**Comment by wjiazheng** [comment]
您好，这篇文章是22年录用的，录用后一直处于early access状态，今年才正式见刊，所以会有这两个日期。引用的话，应当引用2024年更新后有正式期卷号的版本，例如下面这种形式，感谢您的关注！
H. Du, J. Wang, M. Liu, Y. Wang and E. Meijering, "SwinPA-Net: Swin Transformer-Based Multiscale Feature Pyramid Aggregation Network for Medical Image Segmentation," in IEEE Transactions on Neural Networks and Learning Systems, vol. 35, no. 4, pp. 5355-5366, April 2024.

**Comment by 1580827935** [comment]
感谢您的回答
